# Generated by Django 3.0.5 on 2020-05-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_faces_result_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faces',
            name='date',
            field=models.CharField(default='1399/02/14', editable=False, max_length=10),
        ),
    ]
