# Generated by Django 3.0.5 on 2020-05-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0003_auto_20200503_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faces',
            name='date',
            field=models.CharField(default='1399/02/17', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='faces',
            name='result_photo',
            field=models.CharField(max_length=500),
        ),
    ]
